### ISSUE TITLE
Preparation of our research

### ISSUE THREAD

**Issue by zhangxiang0822** [zhangxiang0822/Shifang_research#2]
Several preparation before we actually start our research.

- Get ourselves familiar with Shifang Dataset (Maorui)
    - Try to write up a brief description of Shifang Dataset. Please include the following information:
          - How long is the panel
          - What is the sample size (roughly speaking)
          - What do we have in the dataset? For example, do we have demographic information? Do we have information on the physicians/doctors? Do we have information on the hospital facilities? Etc. Write down anything you think is correlated with our research.
    - Please revise this [wikipage](https://github.com/zhangxiang0822/Shifang_research/wiki/Shifang-county-level-data). Adding more detailed information on the dataset
- Think about identification strategy (Dasuan, Maorui and Xiang)
- More information on Shifang (Xiang)
     - Also revise this [wikipage](https://github.com/zhangxiang0822/Shifang_research/wiki/Shifang-county-level-data)
- Ask Haijing for permission to use this dataset, sign up datause agreement and try to get a 5% sample. (Dasuan)
- Once we have the access to the data, if it's possible to have some summary stats? For example, can we have stats on how many individuals we have in each year, etc. (Maorui and Dasuan)
    - Dasuan could decide which summary stats to have

**Comment by Maorui-Y** [comment]
I uploaded the codebook of Shifang dataset in dropbox, you can see the observations of each var, note, the time span of the old dataset is 2006-2012, the new dataset is 2006-2012. There are some differences between the new dataset and the old dataset, you can also see the detail in the dropbox.

**Comment by dasuanyao** [comment]
Data is available under Xiao Guan's agreement.

**Comment by dasuanyao** [comment]
Finally, I got the data. full sample.
@zhangxiang0822 @Maorui-Y
